services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  server:
    build: .
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules
    command: npm run dev
    environment:
      PORT: 5000
    depends_on:
      - redis
